```{r}
install.packages("tm") # for text mining
install.packages("SnowballC") # for text stemming
```
```{r}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```
```{r}
text <- readLines("nicki.txt", encoding = "UTF-8")
```
```{r}
docs <- Corpus(VectorSource(text)) # load data as a corpus
```
```{r}
inspect(docs)
```
```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
#docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
#docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
#docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
#docs <- tm_map(docs, stemDocument)
```
```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```
```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```
```{r}
findFreqTerms(dtm, lowfreq = 4)
```
```{r}
findAssocs(dtm, terms = "bitch", corlimit = 0.2)
```
```{r}
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word, col="lightblue", main="Most frequent words", ylab = "Word frequencies")
```

